const OZ=(()=>{const KEY="orthozenix_products_v2",LOG="orthozenix_stock_log_v1";
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const products=()=>JSON.parse(localStorage.getItem(KEY)||"[]"), save=a=>localStorage.setItem(KEY,JSON.stringify(a));
const logs=()=>JSON.parse(localStorage.getItem(LOG)||"[]"), saveLogs=a=>localStorage.setItem(LOG,JSON.stringify(a));
const money=n=>Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const status=x=>x.quantity<=0?'<span class="badge out">Out of Stock</span>':x.quantity<=x.minimum_qty?'<span class="badge low">Low Stock</span>':'<span class="badge ok">In Stock</span>';
function log(id,type,amount,before,after){let a=logs();a.unshift({id,type,amount,before,after,date:new Date().toISOString()});saveLogs(a.slice(0,100))}
function change(id,delta){let a=products(),x=a.find(p=>p.id===id);if(!x)return;if(delta<0&&x.quantity<Math.abs(delta))return alert("Not enough stock available.");let before=x.quantity;x.quantity+=delta;save(a);log(id,delta>0?"Stock In":"Stock Out",Math.abs(delta),before,x.quantity);location.reload()}
function del(id){if(!confirm("Delete this product permanently?"))return;save(products().filter(p=>p.id!==id));saveLogs(logs().filter(l=>l.id!==id));location.href="productlist.html"}
function table(a){if(!a.length)return '<div class="empty">No products found.</div>';return `<table class="data-table"><thead><tr><th>Catalogue No.</th><th>Product</th><th>Category</th><th>Material</th><th>Size</th><th>Qty</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>${a.map(x=>`<tr><td><a href="product-details.html?id=${encodeURIComponent(x.id)}">${esc(x.catalogue_no)}</a></td><td>${esc(x.product_name)}</td><td>${esc(x.category)}</td><td>${esc(x.material)}</td><td>${esc(x.size)}</td><td><b>${x.quantity}</b> / min ${x.minimum_qty}</td><td>${money(x.price)}</td><td>${status(x)}</td><td><div class="actions"><button class="mini plus" onclick="OZ.change('${x.id}',1)">＋</button><button class="mini minus" onclick="OZ.change('${x.id}',-1)">−</button><a class="mini" href="editproduct.html?id=${encodeURIComponent(x.id)}">Edit</a><button class="mini danger" onclick="OZ.del('${x.id}')">Delete</button></div></td></tr>`).join("")}</tbody></table>`}
function dashboard(){let a=products(),units=a.reduce((s,x)=>s+Number(x.quantity),0),low=a.filter(x=>x.quantity>0&&x.quantity<=x.minimum_qty).length,out=a.filter(x=>x.quantity<=0).length;$("#totalProducts").textContent=a.length;$("#totalUnits").textContent=units;$("#lowStock").textContent=low;$("#outStock").textContent=out;$("#recentProducts").innerHTML=table(a.slice().sort((x,y)=>y.created-x.created).slice(0,5));let map=new Map(a.map(x=>[x.id,x]));$("#activity").innerHTML=logs().slice(0,8).map(l=>{let p=map.get(l.id);return p?`<div class="activity-row"><span><b>${esc(p.catalogue_no)}</b> — ${l.type} ${l.amount} unit(s)</span><small>${new Date(l.date).toLocaleString()}</small></div>`:""}).join("")||'<div class="empty">No stock activity yet.</div>';
$("#exportBtn").onclick=()=>{let blob=new Blob([JSON.stringify({products:a,logs:logs()},null,2)],{type:"application/json"}),u=URL.createObjectURL(blob),z=document.createElement("a");z.href=u;z.download="orthozenix-inventory-backup.json";z.click();URL.revokeObjectURL(u)};
$("#importFile").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!Array.isArray(d.products))throw Error();save(d.products);saveLogs(Array.isArray(d.logs)?d.logs:[]);alert("Backup imported successfully.");location.reload()}catch{alert("Invalid backup file.")}};r.readAsText(f)}}}
function productsPage(){let all=products(),draw=()=>{let q=$("#search").value.toLowerCase(),f=$("#stockFilter").value,a=all.filter(x=>{let hit=[x.catalogue_no,x.product_name,x.category,x.material,x.size,x.description].join(" ").toLowerCase().includes(q);let st=f==="low"?x.quantity>0&&x.quantity<=x.minimum_qty:f==="out"?x.quantity<=0:f==="in"?x.quantity>x.minimum_qty:true;return hit&&st});$("#productTable").innerHTML=table(a)};$("#search").oninput=draw;$("#stockFilter").onchange=draw;draw()}
function addProduct(){let form=$("#productForm");form.onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(form)),a=products();if(a.some(x=>x.catalogue_no.toLowerCase()===d.catalogue_no.trim().toLowerCase()))return alert("Catalogue No. already exists.");let p={id:crypto.randomUUID(),created:Date.now(),catalogue_no:d.catalogue_no.trim(),product_name:d.product_name.trim(),category:d.category,material:d.material,size:d.size.trim(),quantity:Number(d.quantity)||0,minimum_qty:Number(d.minimum_qty)||0,price:Number(d.price)||0,description:d.description.trim()};a.push(p);save(a);if(p.quantity)log(p.id,"Opening Stock",p.quantity,0,p.quantity);location.href="productlist.html"}}
function editProduct(){let id=new URLSearchParams(location.search).get("id"),x=products().find(p=>p.id===id);if(!x)return location.href="productlist.html";$("#editFields").innerHTML=`<label>Catalogue No. *<input name="catalogue_no" required value="${esc(x.catalogue_no)}"></label><label>Product Name *<input name="product_name" required value="${esc(x.product_name)}"></label><label>Category<input name="category" value="${esc(x.category)}"></label><label>Material<input name="material" value="${esc(x.material)}"></label><label>Size / Specification<input name="size" value="${esc(x.size)}"></label><label>Quantity<input name="quantity" type="number" min="0" value="${x.quantity}"></label><label>Minimum Qty<input name="minimum_qty" type="number" min="0" value="${x.minimum_qty}"></label><label>Price<input name="price" type="number" min="0" step="0.01" value="${x.price}"></label><label class="full">Description<textarea name="description">${esc(x.description)}</textarea></label>`;$("#editForm").onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),a=products();if(a.some(p=>p.id!==id&&p.catalogue_no.toLowerCase()===d.catalogue_no.trim().toLowerCase()))return alert("Catalogue No. already exists.");Object.assign(x,{catalogue_no:d.catalogue_no.trim(),product_name:d.product_name.trim(),category:d.category,material:d.material,size:d.size.trim(),quantity:Number(d.quantity)||0,minimum_qty:Number(d.minimum_qty)||0,price:Number(d.price)||0,description:d.description.trim()});save(a);location.href="product-details.html?id="+encodeURIComponent(id)}}
function details(){let id=new URLSearchParams(location.search).get("id"),x=products().find(p=>p.id===id);if(!x)return location.href="productlist.html";let history=logs().filter(l=>l.id===id).slice(0,10);$("#details").innerHTML=`<div class="detail-grid"><div class="card"><h2 class="detail-title">${esc(x.product_name)}</h2><div class="detail-sub">${esc(x.catalogue_no)}</div><div class="stock-box"><div class="stock-number">${x.quantity}</div>${status(x)}</div><div class="actions" style="margin-top:18px"><button class="btn primary" onclick="OZ.change('${x.id}',1)">＋ Add Stock</button><button class="btn light" onclick="OZ.change('${x.id}',-1)">− Remove Stock</button><a class="btn light" href="editproduct.html?id=${encodeURIComponent(x.id)}">Edit</a><button class="btn light" onclick="OZ.del('${x.id}')">Delete</button></div></div><div class="card"><h2>Product Information</h2><div class="kv"><b>Catalogue No.</b><span>${esc(x.catalogue_no)}</span></div><div class="kv"><b>Category</b><span>${esc(x.category)}</span></div><div class="kv"><b>Material</b><span>${esc(x.material)}</span></div><div class="kv"><b>Size / Specification</b><span>${esc(x.size)||"—"}</span></div><div class="kv"><b>Minimum Qty</b><span>${x.minimum_qty}</span></div><div class="kv"><b>Price</b><span>${money(x.price)}</span></div><div class="kv"><b>Description</b><span>${esc(x.description)||"—"}</span></div></div></div><div class="card"><h2>Stock Activity</h2>${history.map(l=>`<div class="activity-row"><span class="${l.type==="Stock In"||l.type==="Opening Stock"?"positive":"negative"}"><b>${l.type}</b> — ${l.amount} unit(s)</span><small>${new Date(l.date).toLocaleString()} · ${l.before} → ${l.after}</small></div>`).join("")||'<div class="empty">No activity yet.</div>'}</div>`}
return{dashboard,products:productsPage,addProduct,editProduct,details,change,del}})();